audio:
  buffer_size: 1024
  channels: 1
  confidence_threshold: 0.5
  frame_duration_ms: 30
  language: auto
  min_words: 3
  model:
    name: medium
  output_dir: transcripts
  pause_timeout: 1.0
  sample_rate: 16000
  vad:
    aggressiveness: 2
nlp:
  model: gemma3:27b
